In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

In [2]:
iris = load_iris()
X = iris.data[:,2:] #petal length and width
y = iris.target

tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [19]:
X

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.4, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [3]:
import os
os.getcwd()+"/hjkh"
#open(os.getcwd()+"/iris_tree.dot", 'w')

'/Volumes/lin/MachineLearning/hjkh'

In [11]:
from sklearn.tree import export_graphviz

path = os.getcwd()+"/"
export_graphviz(
    tree_clf,
    out_file=".iris_tree.dot",
    feature_names=iris.feature_names[2:],
    class_names=iris.target_names,
    rounded=True,
    filled=True
)

In [16]:
#dot -Tpng iris_tree.dot -o iris_tree.png
#to run graphviz from cmd line

SyntaxError: invalid syntax (<ipython-input-16-7bda9265f286>, line 1)

In [ ]:
#EXERCISE 7

In [59]:
import numpy as np

In [20]:
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=10000, noise=0.4, random_state=42)

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
from sklearn.model_selection import GridSearchCV

params = {'max_leaf_nodes': list(range(2, 100)), 'min_samples_split': [2, 3, 4]}
grid_search_cv = GridSearchCV(DecisionTreeClassifier(random_state=42), params, 
                              n_jobs=-1, verbose=1, cv=3
                             ,refit=False)

In [ ]:
grid_search_cv.fit(X_train, y_train)

In [ ]:
grid_search_cv.best_estimator_

In [ ]:
from sklearn.metrics import accuracy_score

y_pred = grid_search_cv.predict(X_test)
accuracy_score(y_test, y_pred)

In [ ]:
#EXERCISE 8

In [23]:
from sklearn.model_selection import ShuffleSplit

n_trees = 1000
n_instances = 100

mini_sets = []

rs = ShuffleSplit(n_splits=n_trees, test_size=len(X_train) - n_instances, random_state=42)
for mini_train_index, mini_test_index in rs.split(X_train):
    X_mini_train = X_train[mini_train_index]
    y_mini_train = y_train[mini_train_index]
    mini_sets.append((X_mini_train, y_mini_train))

In [62]:
print(len(mini_sets)) #number of rows
print(len(mini_sets[1])) #number of columns
print(type(mini_sets))

1000
2
<class 'list'>


In [91]:
mini_sets[0][:2] # mini_sets[0][:2] == mini_sets[0]

(array([[-3.15325488e-01,  4.94322659e-01],
        [ 1.07395888e+00, -3.83006874e-01],
        [ 1.23368080e+00, -2.02727544e-01],
        [ 1.45327595e+00, -4.97650493e-01],
        [ 6.29403125e-01, -4.58057181e-01],
        [ 1.31621613e+00, -4.96340629e-01],
        [ 6.61605020e-01, -5.25120656e-01],
        [ 1.17772151e+00,  2.12896730e-01],
        [ 1.27074026e+00,  8.37618484e-01],
        [ 2.40777741e-01, -4.05280317e-01],
        [ 2.09601211e+00,  2.29976411e-01],
        [ 3.96488095e-01, -3.07170096e-01],
        [-7.76673348e-01,  1.98996929e-01],
        [-8.88960092e-01,  1.06022488e+00],
        [ 1.21458297e+00, -3.55536724e-01],
        [ 1.72720880e+00,  3.94406303e-01],
        [ 1.96647532e+00,  2.91551342e-01],
        [-2.00602385e-01,  4.62530417e-02],
        [-1.19424550e+00,  1.64842526e-01],
        [-2.98171028e-01,  4.07082497e-01],
        [ 2.07327094e+00,  2.02547469e-02],
        [-7.43875589e-01,  1.01769167e+00],
        [-1.03747473e+00,  4.298

In [27]:
len(X_train)

8000

In [30]:
rs.test_size

7900

In [31]:
len(mini_train_index)

100

In [32]:
len(mini_test_index)

7900

In [33]:
mini_train_index

array([2413, 2772, 7346, 7577,  933, 1774, 7913, 1448, 5761, 2705, 4908,
        553,  202, 1925, 4227, 6444, 1016, 2537, 4417, 1182,  612,  830,
       7843, 2288, 3061,  606, 7307, 1972, 6139, 2316, 5323, 5281, 5672,
        866, 5215, 4800, 4761, 6063, 7472, 2578, 4366, 1508, 7023, 2550,
       5623, 6071, 7021,  454, 7640, 4700, 1224, 6214, 3036, 7769,  484,
       5408,  591, 6985, 3085, 2466, 7734, 4378, 3361, 7397, 4182, 5476,
       6557, 3762, 3348, 4732, 5028, 7064, 7003, 4497, 3296, 4998, 2714,
       5758, 5815, 7062, 5910, 5166, 5102, 6384,  611, 4035,  231, 1282,
       2709, 5302, 5909, 6870, 4400, 2377, 1750, 7156, 6526, 4887, 2999,
       3487])